# Generated by Django 5.2 on 2025-04-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_state", models.JSONField(default=list)),
                (
                    "player1_type",
                    models.CharField(
                        choices=[("HUMAN", "Human"), ("AI", "AI")],
                        default="HUMAN",
                        max_length=5,
                    ),
                ),
                (
                    "player2_type",
                    models.CharField(
                        choices=[("HUMAN", "Human"), ("AI", "AI")],
                        default="AI",
                        max_length=5,
                    ),
                ),
                ("current_turn", models.IntegerField(default=1)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Ongoing"),
                            (1, "Player 1 Wins"),
                            (2, "Player 2 Wins"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
