# Generated by Django 5.2 on 2025-04-20 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ai_search_depth",
            field=models.IntegerField(
                default=5,
                help_text="Profundidad de búsqueda para la IA (más alto = más 'inteligente' pero más lento)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
    ]
