# Generated by Django 4.2.20 on 2025-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_ai_search_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="moves_since_progress",
            field=models.IntegerField(
                default=0,
                help_text="Contador de medio-movimientos desde la última captura o movimiento de peón.",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Ongoing"),
                    (1, "Player 1 Wins"),
                    (2, "Player 2 Wins"),
                    (3, "Draw"),
                ],
                default=0,
            ),
        ),
    ]
