# Generated by Django 4.2.20 on 2025-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_game_moves_since_progress_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
