# Generated by Django 4.2.20 on 2025-05-02 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_is_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="limit_draw",
            field=models.IntegerField(
                default=10,
                help_text="Maximo numero de movimientos para tablas,desde 10 (facil) hasta 80 (dificil)",
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(80),
                ],
            ),
        ),
    ]
